# .github/workflows/docker-deploy.yml
name: Deploy API to Azure Container Registry

on:
  push:
    branches:
      - 'main'
    paths:
      - 'apps/api/**'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Setup Node.js environment with version 21.5.0
    - name: Setup Node.js 21.5.0
      uses: actions/setup-node@v3
      with:
        node-version: 21.5.0  # Use Node.js 21.5.0 instead of 20.17.0

    # 3. Install pnpm globally
    - name: Install pnpm
      run: npm install -g pnpm

    # 4. Install dependencies for the API (using `--filter` to only install for the /api app)
    - name: Install dependencies
      run: |
        pnpm install --filter ./apps/api...

    # 5. Log in to Azure Container Registry
    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: surveysproutcontainerregistry1.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    # 6. Build the Docker image (using the /api context)
    - name: Build Docker image
      run: |
        cd apps/api
        docker build --no-cache --platform linux/amd64 -t surveysproutcontainerregistry1.azurecr.io/app:latest .

    # 7. Push the Docker image to Azure Container Registry
    - name: Push Docker image
      run: |
        docker push surveysproutcontainerregistry1.azurecr.io/app:latest
