name: Deploy API to Azure Container Registry

on:
  push:
    paths:
      - 'apps/api/**' # Trigger only when files in the /api directory change
  workflow_dispatch: # Allow manual triggering if needed

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Set up caching for pnpm
    - name: Set up pnpm with caching
      uses: pnpm/action-setup@v2
      with:
        version: 8.6.3 # Use the desired version of pnpm
        cache: true

    # 3. Install dependencies for the API
    - name: Install dependencies
      run: |
        cd apps/api
        pnpm install

    # 4. Log in to Azure Container Registry
    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: surveysproutcontainerregistry1.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    # 5. Build the Docker image
    - name: Build Docker image
      run: |
        cd apps/api
        docker build --no-cache --platform linux/amd64 -t surveysproutcontainerregistry1.azurecr.io/app:latest .

    # 6. Push the Docker image to ACR
    - name: Push Docker image
      run: |
        docker push surveysproutcontainerregistry1.azurecr.io/app:latest
